<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\OrdersV2026;

/**
 * The Selling Partner API for Orders.
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class ConstraintType
{
    /**
     * Possible values of this enum.
     */
    public const MANDATORY = 'MANDATORY';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::MANDATORY,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
