<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\OrdersV2026;

use AmazonPHP\SellingPartner\Exception\AssertionException;
use AmazonPHP\SellingPartner\ModelInterface;
use AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * The Selling Partner API for Orders.
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 *
 * @implements \ArrayAccess<TKey, TValue>
 *
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ItemFulfillment implements \ArrayAccess, \JsonSerializable, \Stringable, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ItemFulfillment';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'quantity_fulfilled' => 'int',
        'quantity_unfulfilled' => 'int',
        'picking' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ItemPicking',
        'packing' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ItemPacking',
        'shipping' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ItemShipping',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'quantity_fulfilled' => null,
        'quantity_unfulfilled' => null,
        'picking' => null,
        'packing' => null,
        'shipping' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'quantity_fulfilled' => 'quantityFulfilled',
        'quantity_unfulfilled' => 'quantityUnfulfilled',
        'picking' => 'picking',
        'packing' => 'packing',
        'shipping' => 'shipping',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'quantity_fulfilled' => 'setQuantityFulfilled',
        'quantity_unfulfilled' => 'setQuantityUnfulfilled',
        'picking' => 'setPicking',
        'packing' => 'setPacking',
        'shipping' => 'setShipping',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'quantity_fulfilled' => 'getQuantityFulfilled',
        'quantity_unfulfilled' => 'getQuantityUnfulfilled',
        'picking' => 'getPicking',
        'packing' => 'getPacking',
        'shipping' => 'getShipping',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['quantity_fulfilled'] = $data['quantity_fulfilled'] ?? null;
        $this->container['quantity_unfulfilled'] = $data['quantity_unfulfilled'] ?? null;
        $this->container['picking'] = $data['picking'] ?? null;
        $this->container['packing'] = $data['packing'] ?? null;
        $this->container['shipping'] = $data['shipping'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString() : string
    {
        return (string) \json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['picking'] !== null) {
            $this->container['picking']->validate();
        }

        if ($this->container['packing'] !== null) {
            $this->container['packing']->validate();
        }

        if ($this->container['shipping'] !== null) {
            $this->container['shipping']->validate();
        }
    }

    /**
     * Gets quantity_fulfilled.
     *
     * @return null|int
     */
    public function getQuantityFulfilled() : ?int
    {
        return $this->container['quantity_fulfilled'];
    }

    /**
     * Sets quantity_fulfilled.
     *
     * @param null|int $quantity_fulfilled the number of units of this item that have been successfully processed and shipped
     */
    public function setQuantityFulfilled(?int $quantity_fulfilled) : self
    {
        $this->container['quantity_fulfilled'] = $quantity_fulfilled;

        return $this;
    }

    /**
     * Gets quantity_unfulfilled.
     *
     * @return null|int
     */
    public function getQuantityUnfulfilled() : ?int
    {
        return $this->container['quantity_unfulfilled'];
    }

    /**
     * Sets quantity_unfulfilled.
     *
     * @param null|int $quantity_unfulfilled the number of units of this item that remain to be processed and shipped
     */
    public function setQuantityUnfulfilled(?int $quantity_unfulfilled) : self
    {
        $this->container['quantity_unfulfilled'] = $quantity_unfulfilled;

        return $this;
    }

    /**
     * Gets picking.
     *
     * @return null|ItemPicking
     */
    public function getPicking() : ?ItemPicking
    {
        return $this->container['picking'];
    }

    /**
     * Sets picking.
     *
     * @param null|ItemPicking $picking picking
     */
    public function setPicking(?ItemPicking $picking) : self
    {
        $this->container['picking'] = $picking;

        return $this;
    }

    /**
     * Gets packing.
     *
     * @return null|ItemPacking
     */
    public function getPacking() : ?ItemPacking
    {
        return $this->container['packing'];
    }

    /**
     * Sets packing.
     *
     * @param null|ItemPacking $packing packing
     */
    public function setPacking(?ItemPacking $packing) : self
    {
        $this->container['packing'] = $packing;

        return $this;
    }

    /**
     * Gets shipping.
     *
     * @return null|ItemShipping
     */
    public function getShipping() : ?ItemShipping
    {
        return $this->container['shipping'];
    }

    /**
     * Sets shipping.
     *
     * @param null|ItemShipping $shipping shipping
     */
    public function setShipping(?ItemShipping $shipping) : self
    {
        $this->container['shipping'] = $shipping;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
