<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\OrdersV2026;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* The Selling Partner API for Orders
*
* The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
*
* The version of the OpenAPI document: 2026-01-01
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ItemShippingConstraints implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ItemShippingConstraints';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'pallet_delivery' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType',
        'cash_on_delivery' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType',
        'signature_confirmation' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType',
        'recipient_identity_verification' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType',
        'recipient_age_verification' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'pallet_delivery' => null,
        'cash_on_delivery' => null,
        'signature_confirmation' => null,
        'recipient_identity_verification' => null,
        'recipient_age_verification' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'pallet_delivery' => 'palletDelivery',
        'cash_on_delivery' => 'cashOnDelivery',
        'signature_confirmation' => 'signatureConfirmation',
        'recipient_identity_verification' => 'recipientIdentityVerification',
        'recipient_age_verification' => 'recipientAgeVerification'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'pallet_delivery' => 'setPalletDelivery',
        'cash_on_delivery' => 'setCashOnDelivery',
        'signature_confirmation' => 'setSignatureConfirmation',
        'recipient_identity_verification' => 'setRecipientIdentityVerification',
        'recipient_age_verification' => 'setRecipientAgeVerification'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'pallet_delivery' => 'getPalletDelivery',
        'cash_on_delivery' => 'getCashOnDelivery',
        'signature_confirmation' => 'getSignatureConfirmation',
        'recipient_identity_verification' => 'getRecipientIdentityVerification',
        'recipient_age_verification' => 'getRecipientAgeVerification'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pallet_delivery'] = $data['pallet_delivery'] ?? null;
        $this->container['cash_on_delivery'] = $data['cash_on_delivery'] ?? null;
        $this->container['signature_confirmation'] = $data['signature_confirmation'] ?? null;
        $this->container['recipient_identity_verification'] = $data['recipient_identity_verification'] ?? null;
        $this->container['recipient_age_verification'] = $data['recipient_age_verification'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
    }


    /**
     * Gets pallet_delivery
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null
     */
    public function getPalletDelivery()
    {
        return $this->container['pallet_delivery'];
    }

    /**
     * Sets pallet_delivery
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null $pallet_delivery pallet_delivery
     *
     * @return self
     */
    public function setPalletDelivery($pallet_delivery) : self
    {
        $this->container['pallet_delivery'] = $pallet_delivery;

        return $this;
    }

    /**
     * Gets cash_on_delivery
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null
     */
    public function getCashOnDelivery()
    {
        return $this->container['cash_on_delivery'];
    }

    /**
     * Sets cash_on_delivery
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null $cash_on_delivery cash_on_delivery
     *
     * @return self
     */
    public function setCashOnDelivery($cash_on_delivery) : self
    {
        $this->container['cash_on_delivery'] = $cash_on_delivery;

        return $this;
    }

    /**
     * Gets signature_confirmation
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null
     */
    public function getSignatureConfirmation()
    {
        return $this->container['signature_confirmation'];
    }

    /**
     * Sets signature_confirmation
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null $signature_confirmation signature_confirmation
     *
     * @return self
     */
    public function setSignatureConfirmation($signature_confirmation) : self
    {
        $this->container['signature_confirmation'] = $signature_confirmation;

        return $this;
    }

    /**
     * Gets recipient_identity_verification
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null
     */
    public function getRecipientIdentityVerification()
    {
        return $this->container['recipient_identity_verification'];
    }

    /**
     * Sets recipient_identity_verification
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null $recipient_identity_verification recipient_identity_verification
     *
     * @return self
     */
    public function setRecipientIdentityVerification($recipient_identity_verification) : self
    {
        $this->container['recipient_identity_verification'] = $recipient_identity_verification;

        return $this;
    }

    /**
     * Gets recipient_age_verification
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null
     */
    public function getRecipientAgeVerification()
    {
        return $this->container['recipient_age_verification'];
    }

    /**
     * Sets recipient_age_verification
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\ConstraintType|null $recipient_age_verification recipient_age_verification
     *
     * @return self
     */
    public function setRecipientAgeVerification($recipient_age_verification) : self
    {
        $this->container['recipient_age_verification'] = $recipient_age_verification;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

