<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\OrdersV2026;

use AmazonPHP\SellingPartner\Exception\AssertionException;
use AmazonPHP\SellingPartner\ModelInterface;
use AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * The Selling Partner API for Orders.
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 *
 * @implements \ArrayAccess<TKey, TValue>
 *
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ItemShipping implements \ArrayAccess, \JsonSerializable, \Stringable, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ItemShipping';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'scheduled_delivery_window' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\DateTimeRange',
        'shipping_constraints' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ItemShippingConstraints',
        'international_shipping' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\ItemInternationalShipping',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'scheduled_delivery_window' => null,
        'shipping_constraints' => null,
        'international_shipping' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'scheduled_delivery_window' => 'scheduledDeliveryWindow',
        'shipping_constraints' => 'shippingConstraints',
        'international_shipping' => 'internationalShipping',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'scheduled_delivery_window' => 'setScheduledDeliveryWindow',
        'shipping_constraints' => 'setShippingConstraints',
        'international_shipping' => 'setInternationalShipping',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'scheduled_delivery_window' => 'getScheduledDeliveryWindow',
        'shipping_constraints' => 'getShippingConstraints',
        'international_shipping' => 'getInternationalShipping',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['scheduled_delivery_window'] = $data['scheduled_delivery_window'] ?? null;
        $this->container['shipping_constraints'] = $data['shipping_constraints'] ?? null;
        $this->container['international_shipping'] = $data['international_shipping'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString() : string
    {
        return (string) \json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['scheduled_delivery_window'] !== null) {
            $this->container['scheduled_delivery_window']->validate();
        }

        if ($this->container['shipping_constraints'] !== null) {
            $this->container['shipping_constraints']->validate();
        }

        if ($this->container['international_shipping'] !== null) {
            $this->container['international_shipping']->validate();
        }
    }

    /**
     * Gets scheduled_delivery_window.
     *
     * @return null|DateTimeRange
     */
    public function getScheduledDeliveryWindow() : ?DateTimeRange
    {
        return $this->container['scheduled_delivery_window'];
    }

    /**
     * Sets scheduled_delivery_window.
     *
     * @param null|DateTimeRange $scheduled_delivery_window scheduled_delivery_window
     */
    public function setScheduledDeliveryWindow(?DateTimeRange $scheduled_delivery_window) : self
    {
        $this->container['scheduled_delivery_window'] = $scheduled_delivery_window;

        return $this;
    }

    /**
     * Gets shipping_constraints.
     *
     * @return null|ItemShippingConstraints
     */
    public function getShippingConstraints() : ?ItemShippingConstraints
    {
        return $this->container['shipping_constraints'];
    }

    /**
     * Sets shipping_constraints.
     *
     * @param null|ItemShippingConstraints $shipping_constraints shipping_constraints
     */
    public function setShippingConstraints(?ItemShippingConstraints $shipping_constraints) : self
    {
        $this->container['shipping_constraints'] = $shipping_constraints;

        return $this;
    }

    /**
     * Gets international_shipping.
     *
     * @return null|ItemInternationalShipping
     */
    public function getInternationalShipping() : ?ItemInternationalShipping
    {
        return $this->container['international_shipping'];
    }

    /**
     * Sets international_shipping.
     *
     * @param null|ItemInternationalShipping $international_shipping international_shipping
     */
    public function setInternationalShipping(?ItemInternationalShipping $international_shipping) : self
    {
        $this->container['international_shipping'] = $international_shipping;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
