<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\OrdersV2026;

use AmazonPHP\SellingPartner\Exception\AssertionException;
use AmazonPHP\SellingPartner\ModelInterface;
use AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * The Selling Partner API for Orders.
 *
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 *
 * @implements \ArrayAccess<TKey, TValue>
 *
 * @template TKey int|null
 * @template TValue mixed|null
 */
class OrderPackage implements \ArrayAccess, \JsonSerializable, \Stringable, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'OrderPackage';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'package_reference_id' => 'string',
        'created_time' => '\DateTimeInterface',
        'package_status' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\PackageStatus',
        'carrier' => 'string',
        'ship_time' => '\DateTimeInterface',
        'shipping_service' => 'string',
        'tracking_number' => 'string',
        'ship_from_address' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\MerchantAddress',
        'package_items' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\PackageItem[]',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'package_reference_id' => null,
        'created_time' => 'date-time',
        'package_status' => null,
        'carrier' => null,
        'ship_time' => 'date-time',
        'shipping_service' => null,
        'tracking_number' => null,
        'ship_from_address' => null,
        'package_items' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'package_reference_id' => 'packageReferenceId',
        'created_time' => 'createdTime',
        'package_status' => 'packageStatus',
        'carrier' => 'carrier',
        'ship_time' => 'shipTime',
        'shipping_service' => 'shippingService',
        'tracking_number' => 'trackingNumber',
        'ship_from_address' => 'shipFromAddress',
        'package_items' => 'packageItems',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'package_reference_id' => 'setPackageReferenceId',
        'created_time' => 'setCreatedTime',
        'package_status' => 'setPackageStatus',
        'carrier' => 'setCarrier',
        'ship_time' => 'setShipTime',
        'shipping_service' => 'setShippingService',
        'tracking_number' => 'setTrackingNumber',
        'ship_from_address' => 'setShipFromAddress',
        'package_items' => 'setPackageItems',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'package_reference_id' => 'getPackageReferenceId',
        'created_time' => 'getCreatedTime',
        'package_status' => 'getPackageStatus',
        'carrier' => 'getCarrier',
        'ship_time' => 'getShipTime',
        'shipping_service' => 'getShippingService',
        'tracking_number' => 'getTrackingNumber',
        'ship_from_address' => 'getShipFromAddress',
        'package_items' => 'getPackageItems',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['package_reference_id'] = $data['package_reference_id'] ?? null;
        $this->container['created_time'] = $data['created_time'] ?? null;
        $this->container['package_status'] = $data['package_status'] ?? null;
        $this->container['carrier'] = $data['carrier'] ?? null;
        $this->container['ship_time'] = $data['ship_time'] ?? null;
        $this->container['shipping_service'] = $data['shipping_service'] ?? null;
        $this->container['tracking_number'] = $data['tracking_number'] ?? null;
        $this->container['ship_from_address'] = $data['ship_from_address'] ?? null;
        $this->container['package_items'] = $data['package_items'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString() : string
    {
        return (string) \json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['package_reference_id'] === null) {
            throw new AssertionException("'package_reference_id' can't be null");
        }

        if ($this->container['package_status'] !== null) {
            $this->container['package_status']->validate();
        }

        if ($this->container['ship_from_address'] !== null) {
            $this->container['ship_from_address']->validate();
        }
    }

    /**
     * Gets package_reference_id.
     *
     * @return string
     */
    public function getPackageReferenceId() : string
    {
        return $this->container['package_reference_id'];
    }

    /**
     * Sets package_reference_id.
     *
     * @param string $package_reference_id a unique identifier for this package within the context of the order
     */
    public function setPackageReferenceId(string $package_reference_id) : self
    {
        $this->container['package_reference_id'] = $package_reference_id;

        return $this;
    }

    /**
     * Gets created_time.
     *
     * @return null|\DateTimeInterface
     */
    public function getCreatedTime() : ?\DateTimeInterface
    {
        return $this->container['created_time'];
    }

    /**
     * Sets created_time.
     *
     * @param null|\DateTimeInterface $created_time The exact time when this shipping package was created and prepared for shipment. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    public function setCreatedTime(?\DateTimeInterface $created_time) : self
    {
        $this->container['created_time'] = $created_time;

        return $this;
    }

    /**
     * Gets package_status.
     *
     * @return null|PackageStatus
     */
    public function getPackageStatus() : ?PackageStatus
    {
        return $this->container['package_status'];
    }

    /**
     * Sets package_status.
     *
     * @param null|PackageStatus $package_status package_status
     */
    public function setPackageStatus(?PackageStatus $package_status) : self
    {
        $this->container['package_status'] = $package_status;

        return $this;
    }

    /**
     * Gets carrier.
     *
     * @return null|string
     */
    public function getCarrier() : ?string
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier.
     *
     * @param null|string $carrier the carrier responsible for transporting this package to the customer
     */
    public function setCarrier(?string $carrier) : self
    {
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets ship_time.
     *
     * @return null|\DateTimeInterface
     */
    public function getShipTime() : ?\DateTimeInterface
    {
        return $this->container['ship_time'];
    }

    /**
     * Sets ship_time.
     *
     * @param null|\DateTimeInterface $ship_time The exact time when this package was handed over to the carrier and began its journey to the customer. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    public function setShipTime(?\DateTimeInterface $ship_time) : self
    {
        $this->container['ship_time'] = $ship_time;

        return $this;
    }

    /**
     * Gets shipping_service.
     *
     * @return null|string
     */
    public function getShippingService() : ?string
    {
        return $this->container['shipping_service'];
    }

    /**
     * Sets shipping_service.
     *
     * @param null|string $shipping_service the specific shipping method or service used for delivering this package
     */
    public function setShippingService(?string $shipping_service) : self
    {
        $this->container['shipping_service'] = $shipping_service;

        return $this;
    }

    /**
     * Gets tracking_number.
     *
     * @return null|string
     */
    public function getTrackingNumber() : ?string
    {
        return $this->container['tracking_number'];
    }

    /**
     * Sets tracking_number.
     *
     * @param null|string $tracking_number the carrier-provided tracking number that customers can use to monitor the package's delivery progress
     */
    public function setTrackingNumber(?string $tracking_number) : self
    {
        $this->container['tracking_number'] = $tracking_number;

        return $this;
    }

    /**
     * Gets ship_from_address.
     *
     * @return null|MerchantAddress
     */
    public function getShipFromAddress() : ?MerchantAddress
    {
        return $this->container['ship_from_address'];
    }

    /**
     * Sets ship_from_address.
     *
     * @param null|MerchantAddress $ship_from_address ship_from_address
     */
    public function setShipFromAddress(?MerchantAddress $ship_from_address) : self
    {
        $this->container['ship_from_address'] = $ship_from_address;

        return $this;
    }

    /**
     * Gets package_items.
     *
     * @return null|PackageItem[]
     */
    public function getPackageItems() : ?array
    {
        return $this->container['package_items'];
    }

    /**
     * Sets package_items.
     *
     * @param null|PackageItem[] $package_items a list of all order items included in this specific package
     */
    public function setPackageItems(?array $package_items) : self
    {
        $this->container['package_items'] = $package_items;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
