<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\OrdersV2026;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* The Selling Partner API for Orders
*
* The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
*
* The version of the OpenAPI document: 2026-01-01
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Order implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'order_id' => 'string',
        'order_aliases' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\Alias[]',
        'created_time' => '\DateTimeInterface',
        'last_updated_time' => '\DateTimeInterface',
        'programs' => 'string[]',
        'associated_orders' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\AssociatedOrder[]',
        'sales_channel' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\SalesChannel',
        'buyer' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\Buyer',
        'recipient' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\Recipient',
        'proceeds' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\OrderProceeds',
        'fulfillment' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\OrderFulfillment',
        'order_items' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\OrderItem[]',
        'packages' => '\AmazonPHP\SellingPartner\Model\OrdersV2026\OrderPackage[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'order_id' => null,
        'order_aliases' => null,
        'created_time' => 'date-time',
        'last_updated_time' => 'date-time',
        'programs' => null,
        'associated_orders' => null,
        'sales_channel' => null,
        'buyer' => null,
        'recipient' => null,
        'proceeds' => null,
        'fulfillment' => null,
        'order_items' => null,
        'packages' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'order_id' => 'orderId',
        'order_aliases' => 'orderAliases',
        'created_time' => 'createdTime',
        'last_updated_time' => 'lastUpdatedTime',
        'programs' => 'programs',
        'associated_orders' => 'associatedOrders',
        'sales_channel' => 'salesChannel',
        'buyer' => 'buyer',
        'recipient' => 'recipient',
        'proceeds' => 'proceeds',
        'fulfillment' => 'fulfillment',
        'order_items' => 'orderItems',
        'packages' => 'packages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'order_id' => 'setOrderId',
        'order_aliases' => 'setOrderAliases',
        'created_time' => 'setCreatedTime',
        'last_updated_time' => 'setLastUpdatedTime',
        'programs' => 'setPrograms',
        'associated_orders' => 'setAssociatedOrders',
        'sales_channel' => 'setSalesChannel',
        'buyer' => 'setBuyer',
        'recipient' => 'setRecipient',
        'proceeds' => 'setProceeds',
        'fulfillment' => 'setFulfillment',
        'order_items' => 'setOrderItems',
        'packages' => 'setPackages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'order_id' => 'getOrderId',
        'order_aliases' => 'getOrderAliases',
        'created_time' => 'getCreatedTime',
        'last_updated_time' => 'getLastUpdatedTime',
        'programs' => 'getPrograms',
        'associated_orders' => 'getAssociatedOrders',
        'sales_channel' => 'getSalesChannel',
        'buyer' => 'getBuyer',
        'recipient' => 'getRecipient',
        'proceeds' => 'getProceeds',
        'fulfillment' => 'getFulfillment',
        'order_items' => 'getOrderItems',
        'packages' => 'getPackages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['order_id'] = $data['order_id'] ?? null;
        $this->container['order_aliases'] = $data['order_aliases'] ?? null;
        $this->container['created_time'] = $data['created_time'] ?? null;
        $this->container['last_updated_time'] = $data['last_updated_time'] ?? null;
        $this->container['programs'] = $data['programs'] ?? null;
        $this->container['associated_orders'] = $data['associated_orders'] ?? null;
        $this->container['sales_channel'] = $data['sales_channel'] ?? null;
        $this->container['buyer'] = $data['buyer'] ?? null;
        $this->container['recipient'] = $data['recipient'] ?? null;
        $this->container['proceeds'] = $data['proceeds'] ?? null;
        $this->container['fulfillment'] = $data['fulfillment'] ?? null;
        $this->container['order_items'] = $data['order_items'] ?? null;
        $this->container['packages'] = $data['packages'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['order_id'] === null) {
            throw new AssertionException("'order_id' can't be null");
        }

        if ($this->container['created_time'] === null) {
            throw new AssertionException("'created_time' can't be null");
        }

        if ($this->container['last_updated_time'] === null) {
            throw new AssertionException("'last_updated_time' can't be null");
        }

        if ($this->container['sales_channel'] === null) {
            throw new AssertionException("'sales_channel' can't be null");
        }

            $this->container['sales_channel']->validate();

            if ($this->container['buyer'] !== null) {
            $this->container['buyer']->validate();
            }

            if ($this->container['recipient'] !== null) {
            $this->container['recipient']->validate();
            }

            if ($this->container['proceeds'] !== null) {
            $this->container['proceeds']->validate();
            }

            if ($this->container['fulfillment'] !== null) {
            $this->container['fulfillment']->validate();
            }

        if ($this->container['order_items'] === null) {
            throw new AssertionException("'order_items' can't be null");
        }

    }


    /**
     * Gets order_id
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string $order_id An Amazon-defined order identifier.
     */
    public function setOrderId($order_id) : self
    {
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets order_aliases
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\Alias[]|null
     */
    public function getOrderAliases()
    {
        return $this->container['order_aliases'];
    }

    /**
     * Sets order_aliases
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\Alias[]|null $order_aliases Alternative identifiers that can be used to reference this order, such as seller-defined order numbers.
     */
    public function setOrderAliases($order_aliases) : self
    {
        $this->container['order_aliases'] = $order_aliases;

        return $this;
    }

    /**
     * Gets created_time
     *
     * @return \DateTimeInterface
     */
    public function getCreatedTime()
    {
        return $this->container['created_time'];
    }

    /**
     * Sets created_time
     *
     * @param \DateTimeInterface $created_time The time when the customer placed the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    public function setCreatedTime($created_time) : self
    {
        $this->container['created_time'] = $created_time;

        return $this;
    }

    /**
     * Gets last_updated_time
     *
     * @return \DateTimeInterface
     */
    public function getLastUpdatedTime()
    {
        return $this->container['last_updated_time'];
    }

    /**
     * Sets last_updated_time
     *
     * @param \DateTimeInterface $last_updated_time The most recent time when any aspect of this order was modified by Amazon or the seller. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     */
    public function setLastUpdatedTime($last_updated_time) : self
    {
        $this->container['last_updated_time'] = $last_updated_time;

        return $this;
    }

    /**
     * Gets programs
     *
     * @return string[]|null
     */
    public function getPrograms()
    {
        return $this->container['programs'];
    }

    /**
     * Sets programs
     *
     * @param string[]|null $programs Special programs associated with this order that may affect fulfillment or customer experience.   **Possible values**: `AMAZON_BAZAAR`, `AMAZON_BUSINESS`,  `AMAZON_EASY_SHIP`, `AMAZON_HAUL`, `DELIVERY_BY_AMAZON`, `FBM_SHIP_PLUS`, `IN_STORE_PICK_UP`, `PREMIUM`, `PREORDER`, `PRIME`
     */
    public function setPrograms($programs) : self
    {
        $this->container['programs'] = $programs;

        return $this;
    }

    /**
     * Gets associated_orders
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\AssociatedOrder[]|null
     */
    public function getAssociatedOrders()
    {
        return $this->container['associated_orders'];
    }

    /**
     * Sets associated_orders
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\AssociatedOrder[]|null $associated_orders Other orders that have a direct relationship to this order, such as replacement or exchange orders.
     */
    public function setAssociatedOrders($associated_orders) : self
    {
        $this->container['associated_orders'] = $associated_orders;

        return $this;
    }

    /**
     * Gets sales_channel
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\SalesChannel
     */
    public function getSalesChannel()
    {
        return $this->container['sales_channel'];
    }

    /**
     * Sets sales_channel
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\SalesChannel $sales_channel sales_channel
     */
    public function setSalesChannel($sales_channel) : self
    {
        $this->container['sales_channel'] = $sales_channel;

        return $this;
    }

    /**
     * Gets buyer
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\Buyer|null
     */
    public function getBuyer()
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\Buyer|null $buyer buyer
     */
    public function setBuyer($buyer) : self
    {
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets recipient
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\Recipient|null
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\Recipient|null $recipient recipient
     */
    public function setRecipient($recipient) : self
    {
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets proceeds
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderProceeds|null
     */
    public function getProceeds()
    {
        return $this->container['proceeds'];
    }

    /**
     * Sets proceeds
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderProceeds|null $proceeds proceeds
     */
    public function setProceeds($proceeds) : self
    {
        $this->container['proceeds'] = $proceeds;

        return $this;
    }

    /**
     * Gets fulfillment
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderFulfillment|null
     */
    public function getFulfillment()
    {
        return $this->container['fulfillment'];
    }

    /**
     * Sets fulfillment
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderFulfillment|null $fulfillment fulfillment
     */
    public function setFulfillment($fulfillment) : self
    {
        $this->container['fulfillment'] = $fulfillment;

        return $this;
    }

    /**
     * Gets order_items
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderItem[]
     */
    public function getOrderItems()
    {
        return $this->container['order_items'];
    }

    /**
     * Sets order_items
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderItem[] $order_items The list of all order items included in this order.
     */
    public function setOrderItems($order_items) : self
    {
        $this->container['order_items'] = $order_items;

        return $this;
    }

    /**
     * Gets packages
     *
     * @return \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderPackage[]|null
     */
    public function getPackages()
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages
     *
     * @param \AmazonPHP\SellingPartner\Model\OrdersV2026\OrderPackage[]|null $packages Shipping packages created for this order, including tracking information. **Note:** Only available for merchant-fulfilled (FBM) orders.
     */
    public function setPackages($packages) : self
    {
        $this->container['packages'] = $packages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString() : string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

