<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShipmentInvoicing;

/**
 * Selling Partner API for Shipment Invoicing.
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * The version of the OpenAPI document: v0
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class PaymentMethodEnum
{
    /**
     * Possible values of this enum.
     */
    public const CREDIT_CARD = 'CreditCard';

    public const DEBIT_CARD = 'DebitCard';

    public const PIX = 'Pix';

    public const BANK_SLIP = 'BankSlip';

    public const GIFT_CARD = 'GiftCard';

    public const OTHER = 'Other';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::CREDIT_CARD,
            self::DEBIT_CARD,
            self::PIX,
            self::BANK_SLIP,
            self::GIFT_CARD,
            self::OTHER,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
