<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShipmentInvoicing;

use AmazonPHP\SellingPartner\Exception\AssertionException;
use AmazonPHP\SellingPartner\ModelInterface;
use AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * Selling Partner API for Shipment Invoicing.
 *
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * The version of the OpenAPI document: v0
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 *
 * @implements \ArrayAccess<TKey, TValue>
 *
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PaymentInformation implements \ArrayAccess, \JsonSerializable, \Stringable, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'PaymentInformation';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'payment_method' => '\AmazonPHP\SellingPartner\Model\ShipmentInvoicing\PaymentMethodEnum',
        'acquirer_id' => 'string',
        'card_brand' => 'string',
        'payment_value' => '\AmazonPHP\SellingPartner\Model\ShipmentInvoicing\Money',
        'authorization_code' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'payment_method' => null,
        'acquirer_id' => null,
        'card_brand' => null,
        'payment_value' => null,
        'authorization_code' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'payment_method' => 'PaymentMethod',
        'acquirer_id' => 'AcquirerId',
        'card_brand' => 'CardBrand',
        'payment_value' => 'PaymentValue',
        'authorization_code' => 'AuthorizationCode',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'payment_method' => 'setPaymentMethod',
        'acquirer_id' => 'setAcquirerId',
        'card_brand' => 'setCardBrand',
        'payment_value' => 'setPaymentValue',
        'authorization_code' => 'setAuthorizationCode',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'payment_method' => 'getPaymentMethod',
        'acquirer_id' => 'getAcquirerId',
        'card_brand' => 'getCardBrand',
        'payment_value' => 'getPaymentValue',
        'authorization_code' => 'getAuthorizationCode',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['payment_method'] = $data['payment_method'] ?? null;
        $this->container['acquirer_id'] = $data['acquirer_id'] ?? null;
        $this->container['card_brand'] = $data['card_brand'] ?? null;
        $this->container['payment_value'] = $data['payment_value'] ?? null;
        $this->container['authorization_code'] = $data['authorization_code'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString() : string
    {
        return (string) \json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['payment_value'] !== null) {
            $this->container['payment_value']->validate();
        }
    }

    /**
     * Gets payment_method.
     *
     * @return null|PaymentMethodEnum
     */
    public function getPaymentMethod() : ?PaymentMethodEnum
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method.
     *
     * @param null|PaymentMethodEnum $payment_method payment_method
     */
    public function setPaymentMethod(?PaymentMethodEnum $payment_method) : self
    {
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets acquirer_id.
     *
     * @return null|string
     */
    public function getAcquirerId() : ?string
    {
        return $this->container['acquirer_id'];
    }

    /**
     * Sets acquirer_id.
     *
     * @param null|string $acquirer_id the government ID of the acquirer
     */
    public function setAcquirerId(?string $acquirer_id) : self
    {
        $this->container['acquirer_id'] = $acquirer_id;

        return $this;
    }

    /**
     * Gets card_brand.
     *
     * @return null|string
     */
    public function getCardBrand() : ?string
    {
        return $this->container['card_brand'];
    }

    /**
     * Sets card_brand.
     *
     * @param null|string $card_brand the credit card brand if the payment method is `CreditCard`
     */
    public function setCardBrand(?string $card_brand) : self
    {
        $this->container['card_brand'] = $card_brand;

        return $this;
    }

    /**
     * Gets payment_value.
     *
     * @return null|Money
     */
    public function getPaymentValue() : ?Money
    {
        return $this->container['payment_value'];
    }

    /**
     * Sets payment_value.
     *
     * @param null|Money $payment_value payment_value
     */
    public function setPaymentValue(?Money $payment_value) : self
    {
        $this->container['payment_value'] = $payment_value;

        return $this;
    }

    /**
     * Gets authorization_code.
     *
     * @return null|string
     */
    public function getAuthorizationCode() : ?string
    {
        return $this->container['authorization_code'];
    }

    /**
     * Sets authorization_code.
     *
     * @param null|string $authorization_code the authorization code of this payment
     */
    public function setAuthorizationCode(?string $authorization_code) : self
    {
        $this->container['authorization_code'] = $authorization_code;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
