generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  modelPackage: Model\ListingsRestrictions
  packageName: ListingsRestrictions
files:
  api.mustache:
    templateType: API
    destinationFilename: /ListingsRestrictionsSDK.php
  api_interface.mustache:
    templateType: API
    destinationFilename: /ListingsRestrictionsSDKInterface.php