<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\VendorShipments;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Selling Partner API for Retail Procurement Shipments
*
* The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
*
* The version of the OpenAPI document: v1
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class RegulationReferences implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'RegulationReferences';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'due_diligence_reference' => 'string',
        'due_diligence_verification' => 'string',
        'due_diligence_information' => 'string',
        'due_diligence_exemption_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'due_diligence_reference' => null,
        'due_diligence_verification' => null,
        'due_diligence_information' => null,
        'due_diligence_exemption_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'due_diligence_reference' => 'dueDiligenceReference',
        'due_diligence_verification' => 'dueDiligenceVerification',
        'due_diligence_information' => 'dueDiligenceInformation',
        'due_diligence_exemption_code' => 'dueDiligenceExemptionCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'due_diligence_reference' => 'setDueDiligenceReference',
        'due_diligence_verification' => 'setDueDiligenceVerification',
        'due_diligence_information' => 'setDueDiligenceInformation',
        'due_diligence_exemption_code' => 'setDueDiligenceExemptionCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'due_diligence_reference' => 'getDueDiligenceReference',
        'due_diligence_verification' => 'getDueDiligenceVerification',
        'due_diligence_information' => 'getDueDiligenceInformation',
        'due_diligence_exemption_code' => 'getDueDiligenceExemptionCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['due_diligence_reference'] = $data['due_diligence_reference'] ?? null;
        $this->container['due_diligence_verification'] = $data['due_diligence_verification'] ?? null;
        $this->container['due_diligence_information'] = $data['due_diligence_information'] ?? null;
        $this->container['due_diligence_exemption_code'] = $data['due_diligence_exemption_code'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
    }


    /**
     * Gets due_diligence_reference
     *
     * @return string|null
     */
    public function getDueDiligenceReference()
    {
        return $this->container['due_diligence_reference'];
    }

    /**
     * Sets due_diligence_reference
     *
     * @param string|null $due_diligence_reference The reference number from the vendor's EUDR Due Diligence Statement (DDS) submitted to the EU Commission portal or provided to Amazon through ONIX feed.
     */
    public function setDueDiligenceReference($due_diligence_reference) : self
    {
        $this->container['due_diligence_reference'] = $due_diligence_reference;

        return $this;
    }

    /**
     * Gets due_diligence_verification
     *
     * @return string|null
     */
    public function getDueDiligenceVerification()
    {
        return $this->container['due_diligence_verification'];
    }

    /**
     * Sets due_diligence_verification
     *
     * @param string|null $due_diligence_verification The EUDR Due Diligence verification number provided by the EU Commission for the submitted DDS.
     */
    public function setDueDiligenceVerification($due_diligence_verification) : self
    {
        $this->container['due_diligence_verification'] = $due_diligence_verification;

        return $this;
    }

    /**
     * Gets due_diligence_information
     *
     * @return string|null
     */
    public function getDueDiligenceInformation()
    {
        return $this->container['due_diligence_information'];
    }

    /**
     * Sets due_diligence_information
     *
     * @param string|null $due_diligence_information The EUDR Due Diligence information pre-loaded in Vendor Central.
     */
    public function setDueDiligenceInformation($due_diligence_information) : self
    {
        $this->container['due_diligence_information'] = $due_diligence_information;

        return $this;
    }

    /**
     * Gets due_diligence_exemption_code
     *
     * @return string|null
     */
    public function getDueDiligenceExemptionCode()
    {
        return $this->container['due_diligence_exemption_code'];
    }

    /**
     * Sets due_diligence_exemption_code
     *
     * @param string|null $due_diligence_exemption_code The exemption code for EUDR products exempt from due diligence requirements.
     */
    public function setDueDiligenceExemptionCode($due_diligence_exemption_code) : self
    {
        $this->container['due_diligence_exemption_code'] = $due_diligence_exemption_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString() : string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

