<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ShippingV2;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Amazon Shipping API
*
* The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
*
* The version of the OpenAPI document: v2
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class AccountType
{
    /**
     * Possible values of this enum
     */
    const SHIPPER_ACCOUNT = 'SHIPPER_ACCOUNT';

    const SHIPPER_ACCOUNT_WITH_INVOICE = 'SHIPPER_ACCOUNT_WITH_INVOICE';

    const AMAZON_ACCOUNT = 'AMAZON_ACCOUNT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::SHIPPER_ACCOUNT,
            self::SHIPPER_ACCOUNT_WITH_INVOICE,
            self::AMAZON_ACCOUNT
        ];
    }

    public function __construct(private readonly string $value)
    {
    }

    public function toString(): string
    {
        return $this->value;
    }
}

