<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

use AmazonPHP\SellingPartner\Exception\AssertionException;
use AmazonPHP\SellingPartner\ModelInterface;
use AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 *
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ChannelDetails implements \ArrayAccess, \JsonSerializable, \Stringable, ModelInterface
{
    final public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ChannelDetails';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'channel_type' => '\AmazonPHP\SellingPartner\Model\ShippingV2\ChannelType',
        'amazon_order_details' => '\AmazonPHP\SellingPartner\Model\ShippingV2\AmazonOrderDetails',
        'amazon_shipment_details' => '\AmazonPHP\SellingPartner\Model\ShippingV2\AmazonShipmentDetails',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'channel_type' => null,
        'amazon_order_details' => null,
        'amazon_shipment_details' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'channel_type' => 'channelType',
        'amazon_order_details' => 'amazonOrderDetails',
        'amazon_shipment_details' => 'amazonShipmentDetails',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'channel_type' => 'setChannelType',
        'amazon_order_details' => 'setAmazonOrderDetails',
        'amazon_shipment_details' => 'setAmazonShipmentDetails',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'channel_type' => 'getChannelType',
        'amazon_order_details' => 'getAmazonOrderDetails',
        'amazon_shipment_details' => 'getAmazonShipmentDetails',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['channel_type'] = $data['channel_type'] ?? null;
        $this->container['amazon_order_details'] = $data['amazon_order_details'] ?? null;
        $this->container['amazon_shipment_details'] = $data['amazon_shipment_details'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return string[]
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return null[]|string[]
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return string[]
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return string[]
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return string[]
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString() : string
    {
        return \json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['channel_type'] === null) {
            throw new AssertionException("'channel_type' can't be null");
        }

        if ($this->container['amazon_order_details'] !== null) {
            $this->container['amazon_order_details']->validate();
        }

        if ($this->container['amazon_shipment_details'] !== null) {
            $this->container['amazon_shipment_details']->validate();
        }
    }

    /**
     * Gets channel_type.
     */
    public function getChannelType() : ChannelType
    {
        return $this->container['channel_type'];
    }

    /**
     * Sets channel_type.
     *
     * @param ChannelType $channel_type channel_type
     */
    public function setChannelType(ChannelType $channel_type) : self
    {
        $this->container['channel_type'] = $channel_type;

        return $this;
    }

    /**
     * Gets amazon_order_details.
     */
    public function getAmazonOrderDetails() : ?AmazonOrderDetails
    {
        return $this->container['amazon_order_details'];
    }

    /**
     * Sets amazon_order_details.
     *
     * @param null|AmazonOrderDetails $amazon_order_details amazon_order_details
     */
    public function setAmazonOrderDetails(?AmazonOrderDetails $amazon_order_details) : self
    {
        $this->container['amazon_order_details'] = $amazon_order_details;

        return $this;
    }

    /**
     * Gets amazon_shipment_details.
     */
    public function getAmazonShipmentDetails() : ?AmazonShipmentDetails
    {
        return $this->container['amazon_shipment_details'];
    }

    /**
     * Sets amazon_shipment_details.
     *
     * @param null|AmazonShipmentDetails $amazon_shipment_details amazon_shipment_details
     */
    public function setAmazonShipmentDetails(?AmazonShipmentDetails $amazon_shipment_details) : self
    {
        $this->container['amazon_shipment_details'] = $amazon_shipment_details;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset) : mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_THROW_ON_ERROR);
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_THROW_ON_ERROR);
    }
}
