<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ShippingV2;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Amazon Shipping API
*
* The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
*
* The version of the OpenAPI document: v2
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class ClaimReason
{
    /**
     * Possible values of this enum
     */
    const LOST_IN_TRANSIT = 'LOST_IN_TRANSIT';

    const DAMAGED_IN_TRANSIT = 'DAMAGED_IN_TRANSIT';

    const DELIVERED_NOT_RECEIVED = 'DELIVERED_NOT_RECEIVED';

    const ITEM_MISSING_SWITCHEROO = 'ITEM_MISSING_SWITCHEROO';

    const COD_ABUSE = 'COD_ABUSE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::LOST_IN_TRANSIT,
            self::DAMAGED_IN_TRANSIT,
            self::DELIVERED_NOT_RECEIVED,
            self::ITEM_MISSING_SWITCHEROO,
            self::COD_ABUSE
        ];
    }

    public function __construct(private readonly string $value)
    {
    }

    public function toString(): string
    {
        return $this->value;
    }
}

