<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class ClaimReason
{
    /**
     * Possible values of this enum.
     */
    public const LOST_IN_TRANSIT = 'LOST_IN_TRANSIT';

    public const DAMAGED_IN_TRANSIT = 'DAMAGED_IN_TRANSIT';

    public const DELIVERED_NOT_RECEIVED = 'DELIVERED_NOT_RECEIVED';

    public const ITEM_MISSING_SWITCHEROO = 'ITEM_MISSING_SWITCHEROO';

    public const COD_ABUSE = 'COD_ABUSE';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::LOST_IN_TRANSIT,
            self::DAMAGED_IN_TRANSIT,
            self::DELIVERED_NOT_RECEIVED,
            self::ITEM_MISSING_SWITCHEROO,
            self::COD_ABUSE,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
