<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ShippingV2;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Amazon Shipping API
*
* The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
*
* The version of the OpenAPI document: v2
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CreateClaimRequest implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'CreateClaimRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'tracking_id' => 'string',
        'declared_value' => '\AmazonPHP\SellingPartner\Model\ShippingV2\Currency',
        'claim_reason' => '\AmazonPHP\SellingPartner\Model\ShippingV2\ClaimReason',
        'is_replacement_package_sent' => 'bool',
        'proofs' => 'string[]',
        'settlement_type' => '\AmazonPHP\SellingPartner\Model\ShippingV2\SettlementType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'tracking_id' => null,
        'declared_value' => null,
        'claim_reason' => null,
        'is_replacement_package_sent' => null,
        'proofs' => null,
        'settlement_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'tracking_id' => 'trackingId',
        'declared_value' => 'declaredValue',
        'claim_reason' => 'claimReason',
        'is_replacement_package_sent' => 'isReplacementPackageSent',
        'proofs' => 'proofs',
        'settlement_type' => 'settlementType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'tracking_id' => 'setTrackingId',
        'declared_value' => 'setDeclaredValue',
        'claim_reason' => 'setClaimReason',
        'is_replacement_package_sent' => 'setIsReplacementPackageSent',
        'proofs' => 'setProofs',
        'settlement_type' => 'setSettlementType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'tracking_id' => 'getTrackingId',
        'declared_value' => 'getDeclaredValue',
        'claim_reason' => 'getClaimReason',
        'is_replacement_package_sent' => 'getIsReplacementPackageSent',
        'proofs' => 'getProofs',
        'settlement_type' => 'getSettlementType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tracking_id'] = $data['tracking_id'] ?? null;
        $this->container['declared_value'] = $data['declared_value'] ?? null;
        $this->container['claim_reason'] = $data['claim_reason'] ?? null;
        $this->container['is_replacement_package_sent'] = $data['is_replacement_package_sent'] ?? null;
        $this->container['proofs'] = $data['proofs'] ?? null;
        $this->container['settlement_type'] = $data['settlement_type'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['tracking_id'] === null) {
            throw new AssertionException("'tracking_id' can't be null");
        }

            if ($this->container['declared_value'] !== null) {
            $this->container['declared_value']->validate();
            }

        if ($this->container['claim_reason'] === null) {
            throw new AssertionException("'claim_reason' can't be null");
        }

        if ($this->container['settlement_type'] === null) {
            throw new AssertionException("'settlement_type' can't be null");
        }

    }


    /**
     * Gets tracking_id
     *
     * @return string
     */
    public function getTrackingId()
    {
        return $this->container['tracking_id'];
    }

    /**
     * Sets tracking_id
     *
     * @param string $tracking_id The carrier generated identifier for a package in a purchased shipment.
     */
    public function setTrackingId($tracking_id) : self
    {
        $this->container['tracking_id'] = $tracking_id;

        return $this;
    }

    /**
     * Gets declared_value
     *
     * @return \AmazonPHP\SellingPartner\Model\ShippingV2\Currency|null
     */
    public function getDeclaredValue()
    {
        return $this->container['declared_value'];
    }

    /**
     * Sets declared_value
     *
     * @param \AmazonPHP\SellingPartner\Model\ShippingV2\Currency|null $declared_value declared_value
     */
    public function setDeclaredValue($declared_value) : self
    {
        $this->container['declared_value'] = $declared_value;

        return $this;
    }

    /**
     * Gets claim_reason
     *
     * @return \AmazonPHP\SellingPartner\Model\ShippingV2\ClaimReason
     */
    public function getClaimReason()
    {
        return $this->container['claim_reason'];
    }

    /**
     * Sets claim_reason
     *
     * @param \AmazonPHP\SellingPartner\Model\ShippingV2\ClaimReason $claim_reason claim_reason
     */
    public function setClaimReason($claim_reason) : self
    {
        $this->container['claim_reason'] = $claim_reason;

        return $this;
    }

    /**
     * Gets is_replacement_package_sent
     *
     * @return bool|null
     */
    public function getIsReplacementPackageSent()
    {
        return $this->container['is_replacement_package_sent'];
    }

    /**
     * Sets is_replacement_package_sent
     *
     * @param bool|null $is_replacement_package_sent Applicable for only On Amazon shipments to identify if replacement was sent
     */
    public function setIsReplacementPackageSent($is_replacement_package_sent) : self
    {
        $this->container['is_replacement_package_sent'] = $is_replacement_package_sent;

        return $this;
    }

    /**
     * Gets proofs
     *
     * @return string[]|null
     */
    public function getProofs()
    {
        return $this->container['proofs'];
    }

    /**
     * Sets proofs
     *
     * @param string[]|null $proofs A list of proof URLs for a claim. Basic URL validation will happen for each URLs present in the list
     */
    public function setProofs($proofs) : self
    {
        $this->container['proofs'] = $proofs;

        return $this;
    }

    /**
     * Gets settlement_type
     *
     * @return \AmazonPHP\SellingPartner\Model\ShippingV2\SettlementType
     */
    public function getSettlementType()
    {
        return $this->container['settlement_type'];
    }

    /**
     * Sets settlement_type
     *
     * @param \AmazonPHP\SellingPartner\Model\ShippingV2\SettlementType $settlement_type settlement_type
     */
    public function setSettlementType($settlement_type) : self
    {
        $this->container['settlement_type'] = $settlement_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString() : string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

