<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class DetailCodes
{
    /**
     * Possible values of this enum.
     */
    final public const BUSINESS_CLOSED = 'BusinessClosed';

    final public const CUSTOMER_UNAVAILABLE = 'CustomerUnavailable';

    final public const PAYMENT_NOT_READY = 'PaymentNotReady';

    final public const OTP_NOT_AVAILABLE = 'OtpNotAvailable';

    final public const DELIVERY_ATTEMPTED = 'DeliveryAttempted';

    final public const UNABLE_TO_ACCESS = 'UnableToAccess';

    final public const UNABLE_TO_CONTACT_RECIPIENT = 'UnableToContactRecipient';

    final public const DELIVERED_TO_BEHIND_WHEELIE_BIN = 'DeliveredToBehindWheelieBin';

    final public const DELIVERED_TO_PORCH = 'DeliveredToPorch';

    final public const DELIVERED_TO_GARAGE = 'DeliveredToGarage';

    final public const DELIVERED_TO_GARDEN = 'DeliveredToGarden';

    final public const DELIVERED_TO_GREENHOUSE = 'DeliveredToGreenhouse';

    final public const DELIVERED_TO_MAIL_SLOT = 'DeliveredToMailSlot';

    final public const DELIVERED_TO_MAIL_ROOM = 'DeliveredToMailRoom';

    final public const DELIVERED_TO_NEIGHBOR = 'DeliveredToNeighbor';

    final public const DELIVERED_TO_REAR_DOOR = 'DeliveredToRearDoor';

    final public const DELIVERED_TO_RECEPTIONIST = 'DeliveredToReceptionist';

    final public const DELIVERED_TO_SHED = 'DeliveredToShed';

    final public const DELIVERED_WITH_OTP = 'DeliveredWithOTP';

    final public const SIGNED = 'Signed';

    final public const DAMAGED = 'Damaged';

    final public const INCORRECT_ITEMS = 'IncorrectItems';

    final public const NOT_REQUIRED = 'NotRequired';

    final public const REJECTED = 'Rejected';

    final public const REJECTED_BY_RECIPIENT_WITH_VERIFICATION = 'RejectedByRecipientWithVerification';

    final public const CANCELLED_BY_RECIPIENT = 'CancelledByRecipient';

    final public const ADDRESS_NOT_FOUND = 'AddressNotFound';

    final public const HAZMAT_SHIPMENT = 'HazmatShipment';

    final public const UNDELIVERABLE = 'Undeliverable';

    final public const ARRIVED_AT_LOCAL_FACILITY = 'ArrivedAtLocalFacility';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::BUSINESS_CLOSED,
            self::CUSTOMER_UNAVAILABLE,
            self::PAYMENT_NOT_READY,
            self::OTP_NOT_AVAILABLE,
            self::DELIVERY_ATTEMPTED,
            self::UNABLE_TO_ACCESS,
            self::UNABLE_TO_CONTACT_RECIPIENT,
            self::DELIVERED_TO_BEHIND_WHEELIE_BIN,
            self::DELIVERED_TO_PORCH,
            self::DELIVERED_TO_GARAGE,
            self::DELIVERED_TO_GARDEN,
            self::DELIVERED_TO_GREENHOUSE,
            self::DELIVERED_TO_MAIL_SLOT,
            self::DELIVERED_TO_MAIL_ROOM,
            self::DELIVERED_TO_NEIGHBOR,
            self::DELIVERED_TO_REAR_DOOR,
            self::DELIVERED_TO_RECEPTIONIST,
            self::DELIVERED_TO_SHED,
            self::DELIVERED_WITH_OTP,
            self::SIGNED,
            self::DAMAGED,
            self::INCORRECT_ITEMS,
            self::NOT_REQUIRED,
            self::REJECTED,
            self::REJECTED_BY_RECIPIENT_WITH_VERIFICATION,
            self::CANCELLED_BY_RECIPIENT,
            self::ADDRESS_NOT_FOUND,
            self::HAZMAT_SHIPMENT,
            self::UNDELIVERABLE,
            self::ARRIVED_AT_LOCAL_FACILITY,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
