<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ShippingV2;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Amazon Shipping API
*
* The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
*
* The version of the OpenAPI document: v2
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class DetailCodes
{
    /**
     * Possible values of this enum
     */
    const BUSINESS_CLOSED = 'BusinessClosed';

    const CUSTOMER_UNAVAILABLE = 'CustomerUnavailable';

    const PAYMENT_NOT_READY = 'PaymentNotReady';

    const OTP_NOT_AVAILABLE = 'OtpNotAvailable';

    const DELIVERY_ATTEMPTED = 'DeliveryAttempted';

    const UNABLE_TO_ACCESS = 'UnableToAccess';

    const UNABLE_TO_CONTACT_RECIPIENT = 'UnableToContactRecipient';

    const DELIVERED_TO_BEHIND_WHEELIE_BIN = 'DeliveredToBehindWheelieBin';

    const DELIVERED_TO_PORCH = 'DeliveredToPorch';

    const DELIVERED_TO_GARAGE = 'DeliveredToGarage';

    const DELIVERED_TO_GARDEN = 'DeliveredToGarden';

    const DELIVERED_TO_GREENHOUSE = 'DeliveredToGreenhouse';

    const DELIVERED_TO_MAIL_SLOT = 'DeliveredToMailSlot';

    const DELIVERED_TO_MAIL_ROOM = 'DeliveredToMailRoom';

    const DELIVERED_TO_NEIGHBOR = 'DeliveredToNeighbor';

    const DELIVERED_TO_REAR_DOOR = 'DeliveredToRearDoor';

    const DELIVERED_TO_RECEPTIONIST = 'DeliveredToReceptionist';

    const DELIVERED_TO_SHED = 'DeliveredToShed';

    const DELIVERED_WITH_OTP = 'DeliveredWithOTP';

    const SIGNED = 'Signed';

    const DAMAGED = 'Damaged';

    const INCORRECT_ITEMS = 'IncorrectItems';

    const NOT_REQUIRED = 'NotRequired';

    const REJECTED = 'Rejected';

    const REJECTED_BY_RECIPIENT_WITH_VERIFICATION = 'RejectedByRecipientWithVerification';

    const CANCELLED_BY_RECIPIENT = 'CancelledByRecipient';

    const ADDRESS_NOT_FOUND = 'AddressNotFound';

    const HAZMAT_SHIPMENT = 'HazmatShipment';

    const UNDELIVERABLE = 'Undeliverable';

    const ARRIVED_AT_LOCAL_FACILITY = 'ArrivedAtLocalFacility';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::BUSINESS_CLOSED,
            self::CUSTOMER_UNAVAILABLE,
            self::PAYMENT_NOT_READY,
            self::OTP_NOT_AVAILABLE,
            self::DELIVERY_ATTEMPTED,
            self::UNABLE_TO_ACCESS,
            self::UNABLE_TO_CONTACT_RECIPIENT,
            self::DELIVERED_TO_BEHIND_WHEELIE_BIN,
            self::DELIVERED_TO_PORCH,
            self::DELIVERED_TO_GARAGE,
            self::DELIVERED_TO_GARDEN,
            self::DELIVERED_TO_GREENHOUSE,
            self::DELIVERED_TO_MAIL_SLOT,
            self::DELIVERED_TO_MAIL_ROOM,
            self::DELIVERED_TO_NEIGHBOR,
            self::DELIVERED_TO_REAR_DOOR,
            self::DELIVERED_TO_RECEPTIONIST,
            self::DELIVERED_TO_SHED,
            self::DELIVERED_WITH_OTP,
            self::SIGNED,
            self::DAMAGED,
            self::INCORRECT_ITEMS,
            self::NOT_REQUIRED,
            self::REJECTED,
            self::REJECTED_BY_RECIPIENT_WITH_VERIFICATION,
            self::CANCELLED_BY_RECIPIENT,
            self::ADDRESS_NOT_FOUND,
            self::HAZMAT_SHIPMENT,
            self::UNDELIVERABLE,
            self::ARRIVED_AT_LOCAL_FACILITY
        ];
    }

    public function __construct(private readonly string $value)
    {
    }

    public function toString(): string
    {
        return $this->value;
    }
}

