<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

use AmazonPHP\SellingPartner\Exception\AssertionException;
use AmazonPHP\SellingPartner\ModelInterface;
use AmazonPHP\SellingPartner\ObjectSerializer;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 *
 * @template TKey int|null
 * @template TValue mixed|null
 */
class DirectPurchaseRequest implements \ArrayAccess, \JsonSerializable, \Stringable, ModelInterface
{
    final public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'DirectPurchaseRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'ship_to' => '\AmazonPHP\SellingPartner\Model\ShippingV2\Address',
        'ship_from' => '\AmazonPHP\SellingPartner\Model\ShippingV2\Address',
        'return_to' => '\AmazonPHP\SellingPartner\Model\ShippingV2\Address',
        'packages' => '\AmazonPHP\SellingPartner\Model\ShippingV2\Package[]',
        'channel_details' => '\AmazonPHP\SellingPartner\Model\ShippingV2\ChannelDetails',
        'label_specifications' => '\AmazonPHP\SellingPartner\Model\ShippingV2\RequestedDocumentSpecification',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'ship_to' => null,
        'ship_from' => null,
        'return_to' => null,
        'packages' => null,
        'channel_details' => null,
        'label_specifications' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'ship_to' => 'shipTo',
        'ship_from' => 'shipFrom',
        'return_to' => 'returnTo',
        'packages' => 'packages',
        'channel_details' => 'channelDetails',
        'label_specifications' => 'labelSpecifications',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'ship_to' => 'setShipTo',
        'ship_from' => 'setShipFrom',
        'return_to' => 'setReturnTo',
        'packages' => 'setPackages',
        'channel_details' => 'setChannelDetails',
        'label_specifications' => 'setLabelSpecifications',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'ship_to' => 'getShipTo',
        'ship_from' => 'getShipFrom',
        'return_to' => 'getReturnTo',
        'packages' => 'getPackages',
        'channel_details' => 'getChannelDetails',
        'label_specifications' => 'getLabelSpecifications',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ship_to'] = $data['ship_to'] ?? null;
        $this->container['ship_from'] = $data['ship_from'] ?? null;
        $this->container['return_to'] = $data['return_to'] ?? null;
        $this->container['packages'] = $data['packages'] ?? null;
        $this->container['channel_details'] = $data['channel_details'] ?? null;
        $this->container['label_specifications'] = $data['label_specifications'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return string[]
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return null[]|string[]
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return string[]
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return string[]
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return string[]
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * Gets the string presentation of the object.
     */
    public function __toString() : string
    {
        return \json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * The original name of the model.
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if ($this->container['ship_to'] !== null) {
            $this->container['ship_to']->validate();
        }

        if ($this->container['ship_from'] !== null) {
            $this->container['ship_from']->validate();
        }

        if ($this->container['return_to'] !== null) {
            $this->container['return_to']->validate();
        }

        if ($this->container['channel_details'] === null) {
            throw new AssertionException("'channel_details' can't be null");
        }

        $this->container['channel_details']->validate();

        if ($this->container['label_specifications'] !== null) {
            $this->container['label_specifications']->validate();
        }
    }

    /**
     * Gets ship_to.
     */
    public function getShipTo() : ?Address
    {
        return $this->container['ship_to'];
    }

    /**
     * Sets ship_to.
     *
     * @param null|Address $ship_to ship_to
     */
    public function setShipTo(?Address $ship_to) : self
    {
        $this->container['ship_to'] = $ship_to;

        return $this;
    }

    /**
     * Gets ship_from.
     */
    public function getShipFrom() : ?Address
    {
        return $this->container['ship_from'];
    }

    /**
     * Sets ship_from.
     *
     * @param null|Address $ship_from ship_from
     */
    public function setShipFrom(?Address $ship_from) : self
    {
        $this->container['ship_from'] = $ship_from;

        return $this;
    }

    /**
     * Gets return_to.
     */
    public function getReturnTo() : ?Address
    {
        return $this->container['return_to'];
    }

    /**
     * Sets return_to.
     *
     * @param null|Address $return_to return_to
     */
    public function setReturnTo(?Address $return_to) : self
    {
        $this->container['return_to'] = $return_to;

        return $this;
    }

    /**
     * Gets packages.
     *
     * @return null|\AmazonPHP\SellingPartner\Model\ShippingV2\Package[]
     */
    public function getPackages() : ?array
    {
        return $this->container['packages'];
    }

    /**
     * Sets packages.
     *
     * @param null|\AmazonPHP\SellingPartner\Model\ShippingV2\Package[] $packages a list of packages to be shipped through a shipping service offering
     */
    public function setPackages(?array $packages) : self
    {
        $this->container['packages'] = $packages;

        return $this;
    }

    /**
     * Gets channel_details.
     */
    public function getChannelDetails() : ChannelDetails
    {
        return $this->container['channel_details'];
    }

    /**
     * Sets channel_details.
     *
     * @param ChannelDetails $channel_details channel_details
     */
    public function setChannelDetails(ChannelDetails $channel_details) : self
    {
        $this->container['channel_details'] = $channel_details;

        return $this;
    }

    /**
     * Gets label_specifications.
     */
    public function getLabelSpecifications() : ?RequestedDocumentSpecification
    {
        return $this->container['label_specifications'];
    }

    /**
     * Sets label_specifications.
     *
     * @param null|RequestedDocumentSpecification $label_specifications label_specifications
     */
    public function setLabelSpecifications(?RequestedDocumentSpecification $label_specifications) : self
    {
        $this->container['label_specifications'] = $label_specifications;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset) : mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     */
    public function offsetSet($offset, $value) : void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_THROW_ON_ERROR);
    }

    /**
     * Gets a header-safe presentation of the object.
     */
    public function toHeaderValue() : string
    {
        return \json_encode(ObjectSerializer::sanitizeForSerialization($this), JSON_THROW_ON_ERROR);
    }
}
