<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ShippingV2;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Amazon Shipping API
*
* The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
*
* The version of the OpenAPI document: v2
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class DocumentFormat
{
    /**
     * Possible values of this enum
     */
    const PDF = 'PDF';

    const PNG = 'PNG';

    const ZPL = 'ZPL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::PDF,
            self::PNG,
            self::ZPL
        ];
    }

    public function __construct(private readonly string $value)
    {
    }

    public function toString(): string
    {
        return $this->value;
    }
}

