<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\ShippingV2;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Amazon Shipping API
*
* The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
*
* The version of the OpenAPI document: v2
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class EventCode
{
    /**
     * Possible values of this enum
     */
    const READY_FOR_RECEIVE = 'ReadyForReceive';

    const PICKUP_DONE = 'PickupDone';

    const DELIVERED = 'Delivered';

    const DEPARTED = 'Departed';

    const DELIVERY_ATTEMPTED = 'DeliveryAttempted';

    const LOST = 'Lost';

    const OUT_FOR_DELIVERY = 'OutForDelivery';

    const ARRIVED_AT_CARRIER_FACILITY = 'ArrivedAtCarrierFacility';

    const REJECTED = 'Rejected';

    const UNDELIVERABLE = 'Undeliverable';

    const PICKUP_CANCELLED = 'PickupCancelled';

    const RETURN_INITIATED = 'ReturnInitiated';

    const AVAILABLE_FOR_PICKUP = 'AvailableForPickup';

    const RECIPIENT_REQUESTED_ALTERNATE_DELIVERY_TIMING = 'RecipientRequestedAlternateDeliveryTiming';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues(): array
    {
        return [
            self::READY_FOR_RECEIVE,
            self::PICKUP_DONE,
            self::DELIVERED,
            self::DEPARTED,
            self::DELIVERY_ATTEMPTED,
            self::LOST,
            self::OUT_FOR_DELIVERY,
            self::ARRIVED_AT_CARRIER_FACILITY,
            self::REJECTED,
            self::UNDELIVERABLE,
            self::PICKUP_CANCELLED,
            self::RETURN_INITIATED,
            self::AVAILABLE_FOR_PICKUP,
            self::RECIPIENT_REQUESTED_ALTERNATE_DELIVERY_TIMING
        ];
    }

    public function __construct(private readonly string $value)
    {
    }

    public function toString(): string
    {
        return $this->value;
    }
}

