<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class EventCode
{
    /**
     * Possible values of this enum.
     */
    final public const READY_FOR_RECEIVE = 'ReadyForReceive';

    final public const PICKUP_DONE = 'PickupDone';

    final public const DELIVERED = 'Delivered';

    final public const DEPARTED = 'Departed';

    final public const DELIVERY_ATTEMPTED = 'DeliveryAttempted';

    final public const LOST = 'Lost';

    final public const OUT_FOR_DELIVERY = 'OutForDelivery';

    final public const ARRIVED_AT_CARRIER_FACILITY = 'ArrivedAtCarrierFacility';

    final public const REJECTED = 'Rejected';

    final public const UNDELIVERABLE = 'Undeliverable';

    final public const PICKUP_CANCELLED = 'PickupCancelled';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::READY_FOR_RECEIVE,
            self::PICKUP_DONE,
            self::DELIVERED,
            self::DEPARTED,
            self::DELIVERY_ATTEMPTED,
            self::LOST,
            self::OUT_FOR_DELIVERY,
            self::ARRIVED_AT_CARRIER_FACILITY,
            self::REJECTED,
            self::UNDELIVERABLE,
            self::PICKUP_CANCELLED,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
