<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class IneligibilityReasonCode
{
    /**
     * Possible values of this enum.
     */
    final public const NO_COVERAGE = 'NO_COVERAGE';

    final public const PICKUP_SLOT_RESTRICTION = 'PICKUP_SLOT_RESTRICTION';

    final public const UNSUPPORTED_VAS = 'UNSUPPORTED_VAS';

    final public const VAS_COMBINATION_RESTRICTION = 'VAS_COMBINATION_RESTRICTION';

    final public const SIZE_RESTRICTIONS = 'SIZE_RESTRICTIONS';

    final public const WEIGHT_RESTRICTIONS = 'WEIGHT_RESTRICTIONS';

    final public const LATE_DELIVERY = 'LATE_DELIVERY';

    final public const PROGRAM_CONSTRAINTS = 'PROGRAM_CONSTRAINTS';

    final public const TERMS_AND_CONDITIONS_NOT_ACCEPTED = 'TERMS_AND_CONDITIONS_NOT_ACCEPTED';

    final public const UNKNOWN = 'UNKNOWN';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::NO_COVERAGE,
            self::PICKUP_SLOT_RESTRICTION,
            self::UNSUPPORTED_VAS,
            self::VAS_COMBINATION_RESTRICTION,
            self::SIZE_RESTRICTIONS,
            self::WEIGHT_RESTRICTIONS,
            self::LATE_DELIVERY,
            self::PROGRAM_CONSTRAINTS,
            self::TERMS_AND_CONDITIONS_NOT_ACCEPTED,
            self::UNKNOWN,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
