<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\ShippingV2;

/**
 * Amazon Shipping API.
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh */
class LabelAttribute
{
    /**
     * Possible values of this enum.
     */
    public const PACKAGE_CLIENT_REFERENCE_ID = 'PACKAGE_CLIENT_REFERENCE_ID';

    public const SELLER_DISPLAY_NAME = 'SELLER_DISPLAY_NAME';

    public const COLLECT_ON_DELIVERY_AMOUNT = 'COLLECT_ON_DELIVERY_AMOUNT';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::PACKAGE_CLIENT_REFERENCE_ID,
            self::SELLER_DISPLAY_NAME,
            self::COLLECT_ON_DELIVERY_AMOUNT,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
